# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: amd64
        CGO_ENABLED: "0"
      run: go build -trimpath -ldflags '-s -w' -o bin/dnsregion-${{ matrix.os }}-amd64${{ matrix.os == 'windows' && '.exe' || '' }} cmd/*.go

    - name: Upload binaries to release
      uses: actions/upload-artifact@v4
      with:
        name: dnsregion-${{ matrix.os }}-amd64${{ matrix.os == 'windows' && '.exe' || '' }}
        path: bin/dnsregion-${{ matrix.os }}-amd64${{ matrix.os == 'windows' && '.exe' || '' }}

